name: Build Arch ISO with LTS Kernel and ZFS
on:
  workflow_dispatch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: build
        shell: bash
        run: |
          kernel=linux-lts
          name=archlinux-lts-zfs
          build="$PWD/$name"
          build_out="$build/out"
          echo "RELEASE_DATE=$(date +'%Y.%m.%d')" >> ${GITHUB_ENV}
          echo "BUILD_OUTPUT_DIR=$build_out" >> ${GITHUB_ENV}

          [ ! "$(pacman -Q archiso)" ] && pacman -Syy --noconfirm archiso
          cp -r /usr/share/archiso/configs/releng "$build"

          sed -i "s/^linux$/$kernel/" "$build"/packages.x86_64

          pkg_add=(
          "zfs-$kernel"
          "$kernel-headers"
          )
          for a in "${pkg_add[@]}" ; do
              echo "$a" >> "$build"/packages.x86_64 
          done

          pkg_rmv=(
          broadcom-wl
          b43-fwcutter
          )
          for a in "${pkg_rmv[@]}" ; do
              sed -i "/$a/d" "$build"/packages.x86_64 
          done

          cd "$build"/airootfs/etc/mkinitcpio.d
          mv linux.preset "$kernel".preset
          sed -i "s/vmlinuz-linux/vmlinuz-$kernel/" "$kernel".preset
          sed -i "s/initramfs-linux.img/initramfs-$kernel.img/" "$kernel".preset

          cd "$build"/syslinux
          sed -i "s/vmlinuz-linux/vmlinuz-$kernel/" archiso_sys-linux.cfg
          sed -i "s/initramfs-linux.img/initramfs-$kernel.img/" archiso_sys-linux.cfg
          sed -i "s/vmlinuz-linux/vmlinuz-$kernel/" archiso_pxe-linux.cfg
          sed -i "s/initramfs-linux.img/initramfs-$kernel.img/" archiso_pxe-linux.cfg

          cd "$build"/efiboot/loader/entries
          sed -i "s/vmlinuz-linux/vmlinuz-$kernel/" 01-archiso-x86_64-linux.conf
          sed -i "s/initramfs-linux.img/initramfs-$kernel.img/" 01-archiso-x86_64-linux.conf
          sed -i "s/vmlinuz-linux/vmlinuz-$kernel/" 02-archiso-x86_64-speech-linux.conf
          sed -i "s/initramfs-linux.img/initramfs-$kernel.img/" 02-archiso-x86_64-speech-linux.conf

          cp "$build"/pacman.conf "$build"/airootfs/etc/pacman.conf
          mkdir -p "$build"/airootfs/usr/share/pacman/keyrings
          echo -e "\n[archzfs]\nSigLevel = Never\nServer = https://github.com/archzfs/archzfs/releases/download/experimental" >> "$build"/pacman.conf
          echo -e "\n[archzfs]\nServer = https://github.com/archzfs/archzfs/releases/download/experimental" >> "$build"/airootfs/etc/pacman.conf
          echo -e "3A9917BF0DED5C13F69AC68FABEC0A1208037BE9:4:" >> "$build"/airootfs/usr/share/pacman/keyrings/archzfs-trusted
          echo -e "-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nmDMEZwfegRYJKwYBBAHaRw8BAQdApTEe98tOu58rF+0NUGXXx/VxenWgb0VjnvBx\niSEYUcK0LEFyY2haRlMgUHJvamVjdCAoaHR0cHM6Ly9naXRodWIuY29tL2FyY2h6\nZnMpiJgEExYKAEAWIQQ6mRe/De1cE/aaxo+r7AoSCAN76QUCZwfegQIbAwsLCQoN\nCAwHCwQDAgcVCgkICwIDBRYCAwEAAh4FAheAAAoJEKvsChIIA3vpfFAA/2XBSvSt\nhopEFZOqY25peeXAXfl7ufCXolvGEE9iSh1sAQDm08strIIy0SNZtMtWg7r70tCw\n7I6z1M7liy+rfgLBDw==\n=SxXd\n-----END PGP PUBLIC KEY BLOCK-----" >> "$build"/airootfs/usr/share/pacman/keyrings/archzfs.gpg

          echo -e '\n\t\033[1m' 'Welcome to Arch Linux LTS with OpenZFS' '\033[0m\n' > "$build"/airootfs/etc/motd
          profile="$build"/profiledef.sh
          sed -i "s/iso_name=\"archlinux\"/iso_name=\"archlinux-lts-zfs\"/" "$profile"
          sed -i "s/iso_label=\"ARCH_\$(date +%Y%m)\"/iso_label=\"ArchLTSZFS_\$(date +%Y-%m-%d)\"/" "$profile" 
          sed -i "s/Installation_guide/archonzfs/" "$profile"
          sed -i "s/livecd-sound/chroot_config/" "$profile"
          sed -i "/choose-mirror/d" "$profile"

          [ -d /tmp/"$name" ] && cd /tmp ; rm -rf "$name"
          mkarchiso -v -w /tmp/"$name" -o "$build_out" "$build"
          ls -alh "$build_out"
      - name: publish
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.BUILD_OUTPUT_DIR }}/archlinux-lts-zfs*
          asset_name: archlinux-lts-zfs-${{ env.RELEASE_DATE }}.iso
          tag: ${{ env.RELEASE_DATE }}
          overwrite: true